---
title: "Ejercicio ETS"
format: html
---

```{r}
library(tidyverse)
library(fpp3)
library(tidyquant)
library(fable)
```

```{r}
vm_raw <- tq_get(
  "TRFVOLUSM227NFWA",
  get  = "economic.data",
  from = "1970-01-01"
)
```

```{r}
vm_tsb <- vm_raw |>
  mutate(date = yearmonth(date)) |>
  as_tsibble(index = date)
```

```{r}
h <- 36

vm_train <- vm_tsb |>
  slice_head(n = nrow(vm_tsb) - h)
```

```{r}
vm_train |>
  autoplot(price) +
  labs(
    title = "U.S. Vehicle Miles Traveled — Training Set",
    subtitle = "Billions of miles, not seasonally adjusted",
    y = "Billions of miles"
  )
```

```{r}
vm_train |>
  autoplot(log(price)) +
  labs(title = "Log-Transformed Vehicle Miles")
```


```{r}
lambda <- vm_train |>
  features(price, features = guerrero) |>
  pull(lambda_guerrero)

lambda
```


```{r}
vm_train |>
  autoplot(box_cox(price, lambda)) +
  labs(
    title = "Box-Cox Transformed Vehicle Miles",
    subtitle = paste0("Guerrero \u03bb = ", round(lambda, 3))
  )
```




```{r Ejercicio 1}
vm_fit_ex <- vm_train |>
  model(
    baseline = decomposition_model(
      STL(box_cox(price, lambda), robust = TRUE),
      RW(season_adjust ~ drift())
    ),
      decomp_arima = decomposition_model(
      STL(box_cox(price, lambda), robust = TRUE),
      ARIMA(season_adjust)
    ),
    
    decomp_explicit_season = decomposition_model(
      STL(box_cox(price, lambda), robust = TRUE),
      RW(season_adjust ~ drift()),
      SNAIVE(season_year) 
    )
  )

vm_fit_ex |>
  forecast(h = h) |>
  accuracy(vm_tsb) |>
  arrange(MAPE)
```


```{r Ejercicio 2}
fit_raw <- vm_train |>
  model(baseline_raw = decomposition_model(
    STL(price, robust = TRUE),
    RW(season_adjust ~ drift())
  ))

fit_log <- vm_train |>
  model(baseline_log = decomposition_model(
    STL(log(price), robust = TRUE),
    RW(season_adjust ~ drift())
  ))

fit_boxcox <- vm_train |>
  model(baseline_boxcox = decomposition_model(
    STL(box_cox(price, lambda), robust = TRUE),
    RW(season_adjust ~ drift())
  ))

bind_rows(
  fit_raw |> 
    forecast(h = h) |> 
    accuracy(vm_tsb),
  fit_log |> 
    forecast(h = h) |> 
    accuracy(vm_tsb),
  fit_boxcox |> 
    forecast(h = h) |> 
    accuracy(vm_tsb)
) |>
  select(.model, .type, MAPE, RMSSE) |>
  arrange(MAPE)
```



```{r}
vm_train |> 
  model(STL(price, robust = TRUE)) |> 
  components() |> 
  autoplot()
vm_train |> 
  model(STL(log(price), robust = TRUE)) |> 
  components() |> 
  autoplot()
vm_train |> 
  model(STL(box_cox(price, lambda), robust = TRUE)) |> 
  components() |> 
  autoplot()
```